const defaultMembers = [
  {name:'遠藤 さくら', gen:'4期生', image:''},{name:'賀喜 遥香', gen:'4期生', image:''},{name:'筒井 あやめ', gen:'4期生', image:''},{name:'田村 真佑', gen:'4期生', image:''},{name:'弓木 奈於', gen:'4期生', image:''},{name:'黒見 明香', gen:'4期生', image:''},{name:'林 瑠奈', gen:'4期生', image:''},{name:'松尾 美佑', gen:'4期生', image:''},{name:'佐藤 璃果', gen:'4期生', image:''},{name:'柴田 柚菜', gen:'4期生', image:''},
  {name:'五百城 茉央', gen:'5期生', image:''},{name:'池田 瑛紗', gen:'5期生', image:''},{name:'一ノ瀬 美空', gen:'5期生', image:''},{name:'井上 和', gen:'5期生', image:''},{name:'小川 彩', gen:'5期生', image:''},{name:'奥田 いろは', gen:'5期生', image:''},{name:'川﨑 桜', gen:'5期生', image:''},{name:'菅原 咲月', gen:'5期生', image:''},{name:'冨里 奈央', gen:'5期生', image:''},{name:'中西 アルノ', gen:'5期生', image:''},
  {name:'愛宕 心響', gen:'6期生', image:''},{name:'大越 ひなの', gen:'6期生', image:''},{name:'小津 玲奈', gen:'6期生', image:''},{name:'海邉 朱莉', gen:'6期生', image:''},{name:'川端 晃菜', gen:'6期生', image:''},{name:'鈴木 佑捺', gen:'6期生', image:''},{name:'瀬戸口 心月', gen:'6期生', image:''},{name:'長嶋 凛桜', gen:'6期生', image:''},{name:'増田 三莉音', gen:'6期生', image:''},{name:'森平 麗心', gen:'6期生', image:''},{name:'矢田 萌華', gen:'6期生', image:''}
];
let members = structuredClone(defaultMembers);
let rows = [[], [], []];
const $ = id => document.getElementById(id);
function initials(name){return name.replace(/\s/g,'').slice(0,2)}
function card(member){const div=document.createElement('div');div.className='member-card';div.dataset.name=member.name;div.innerHTML=`<div class="avatar" ${member.image?`style="background-image:url('${member.image}')"`:''}>${member.image?'':initials(member.name)}</div><div class="name">${member.name}</div><div class="gen">${member.gen}</div>`;return div}
function renderFormation(){ $('formationTitle').textContent=$('titleInput').value || 'オリジナル選抜フォーメーション'; const counts=[+$('frontCount').value,+$('middleCount').value,+$('backCount').value]; const names=['1列目','2列目','3列目']; const root=$('formation'); root.innerHTML=''; rows=rows.map((r,i)=>r.slice(0,counts[i])); counts.forEach((count,i)=>{const row=document.createElement('div'); row.className='row'; for(let j=0;j<count;j++){const slot=document.createElement('div'); slot.className='slot'+(rows[i][j]?' filled':''); slot.dataset.row=i; slot.dataset.index=j; if(rows[i][j]){const m=members.find(x=>x.name===rows[i][j]) || {name:rows[i][j],gen:'',image:''}; const c=card(m); c.onclick=()=>{rows[i][j]=null; rows[i]=rows[i].filter(Boolean); renderAll()}; slot.innerHTML=''; slot.appendChild(c)} else slot.textContent=names[i]; row.appendChild(slot)} root.appendChild(row)})}
function renderMembers(){const q=$('search').value.trim().toLowerCase(); const used=new Set(rows.flat().filter(Boolean)); const box=$('members'); box.innerHTML=''; members.filter(m=>(m.name+m.gen).toLowerCase().includes(q)).forEach(m=>{const c=card(m); if(used.has(m.name)) c.classList.add('selected'); c.onclick=()=>addMember(m.name); box.appendChild(c)})}
function addMember(name){if(rows.flat().includes(name)) return; const counts=[+$('frontCount').value,+$('middleCount').value,+$('backCount').value]; for(let r=0;r<3;r++){if(rows[r].filter(Boolean).length<counts[r]){rows[r].push(name); renderAll(); return}} alert('空き枠がありません。')}
function renderJson(){ $('memberJson').value=JSON.stringify(members,null,2)}
function renderAll(){renderFormation(); renderMembers(); makeShareText()}
function makeShareText(){const text=[$('titleInput').value,'',...rows.map((r,i)=>`${i+1}列目：${r.filter(Boolean).join(' / ') || '未設定'}`)].join('\n'); $('shareText').value=text; return text}
async function copyText(){await navigator.clipboard.writeText(makeShareText()); alert('コピーしました')}
function saveLocal(){localStorage.setItem('n46Formation', JSON.stringify({members,rows,title:$('titleInput').value,counts:[$('frontCount').value,$('middleCount').value,$('backCount').value]})); alert('保存しました')}
function loadLocal(){const s=localStorage.getItem('n46Formation'); if(!s) return alert('保存データがありません'); const d=JSON.parse(s); members=d.members||members; rows=d.rows||rows; $('titleInput').value=d.title||''; ['frontCount','middleCount','backCount'].forEach((id,i)=>$(id).value=d.counts?.[i]||$(id).value); renderJson(); renderAll()}
function applyMembers(){try{const data=JSON.parse($('memberJson').value); if(!Array.isArray(data)) throw new Error(); members=data; rows=[[],[],[]]; renderAll()}catch(e){alert('JSONの形式を確認してください')}}
function downloadPng(){const node=$('captureArea'); const w=node.offsetWidth, h=node.offsetHeight; const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">${node.outerHTML}<style>${[...document.styleSheets].map(s=>{try{return [...s.cssRules].map(r=>r.cssText).join('')}catch(e){return''}}).join('')}</style></div></foreignObject></svg>`; const img=new Image(); const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})); img.onload=()=>{const canvas=document.createElement('canvas'); canvas.width=w*2; canvas.height=h*2; const ctx=canvas.getContext('2d'); ctx.scale(2,2); ctx.fillStyle='#fff'; ctx.fillRect(0,0,w,h); ctx.drawImage(img,0,0); URL.revokeObjectURL(url); const a=document.createElement('a'); a.download='formation.png'; a.href=canvas.toDataURL('image/png'); a.click()}; img.src=url}
$('applyRows').onclick=renderAll; $('clearFormation').onclick=()=>{rows=[[],[],[]]; renderAll()}; $('saveLocal').onclick=saveLocal; $('loadLocal').onclick=loadLocal; $('copyText').onclick=copyText; $('applyMembers').onclick=applyMembers; $('resetMembers').onclick=()=>{members=structuredClone(defaultMembers); rows=[[],[],[]]; renderJson(); renderAll()}; $('downloadPng').onclick=downloadPng; $('search').oninput=renderMembers; $('titleInput').oninput=renderAll; renderJson(); renderAll();
